### ISSUE TITLE
Upload speed not throttled

### ISSUE THREAD

**Issue by Ajaay** [sitespeedio/throttle#10]
Hi,

As the title suggests, I can't get the upload speed to throttle. Download is throttling as expected.

Any ideas?

I'm on 10.13.2

Thanks

**Comment by soulgalore** [comment]
Hi @Ajaay ok, must be bug then, mostly used this for testing web pages so the upload speed isn't so important. Do you have a good way of testing so I can replicate and look into how we set up the rules?

Best
Peter
