### ISSUE TITLE
Building docker fails with "COPY failed: no source files were specified"

### ISSUE THREAD

**Issue by george-haddad** [sitespeedio/throttle#17]
I tried building the docker

```bash
git clone https://github.com/sitespeedio/throttle.git
cd throttle
cd test
docker build -t throttle-docker .
```

It ends with an error

```bash
Sending build context to Docker daemon  3.072kB
Step 1/10 : FROM sitespeedio/node:ubuntu-18.04-nodejs8.11.1
 ---> 52f5b0d0bb0f
Step 2/10 : RUN apt-get update && apt-get install libnss3-tools iproute2 sudo net-tools -y
 ---> Using cache
 ---> 4e0415b2ad4b
Step 3/10 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> a243958c7ce7
Step 4/10 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 77363c4b1136
Step 5/10 : VOLUME /browsertime
 ---> Using cache
 ---> 13b706872893
Step 6/10 : COPY package.* /usr/src/app/
COPY failed: no source files were specified
```

Is this normal? am I missing something?

A little background here. I want to run the network tests on a windows machine, I already know what `throttle` only works on Mac and Linux but there was a section about running this from inside a docker. And this is important for me to get cross platform consistency of running this test. Also it's nice to run everything in a docker if I wish to automate this on a CI like circle.

The docs wasn't 100% clear if this was the strategy, to build a docker that has support for `throttle` from there to build the docker networks and run the performance tests.

**Comment by soulgalore** [comment]
Hey @george-haddad I think it's a bug, the Dockerfile is in the `test/` folder, I think we used it just in the beginning to try it out or something, we don't use it now. If you move up the Dockerfile one level up in the tree it could work.

Best
Peter

**Comment by george-haddad** [comment]
Alright thanks I'll have to give that go on Monday (already left the office)

**Comment by george-haddad** [comment]
it worked

**Comment by soulgalore** [comment]
Hey @george-haddad sorry I didn't read the full answer. I don't think it will work on Windows (or did it?). On Linux you need give the underlying OS the correct `sudo modprobe ifb numifbs=1` to work with Docker. Patrick blogged about shaping the network on Windows https://calendar.perfplanet.com/2016/testing-with-realistic-networking-conditions/

**Comment by george-haddad** [comment]
Hey thanks for this link, I'm actually trying to get this to work in a platform independent way. I can get this running on Linux locally, but what I really want is to automate this in CircleCI (or any CI tool) so I was thinking of doing all of this in Dockers. Does this sound feasible?

**Comment by soulgalore** [comment]
I think it's really hard to do it platform independent. What you can do is setup a Linux box and then share that network to boxes (if you run it locally on your own servers).

For CircleCi (or Travis or whatever) you should be able to run it on Linux as long as you have the right privileges, but I haven't tried it myself :)

**Comment by george-haddad** [comment]
Alright no problem, yeah I'll look into that. I was thinking that I can definitely get this self-contained in a Linux VM image, though I wanted something that can be run a bit easier so I thought if I stuffed it all in a docker. It's not the best thing to have a docker spawn dockers inside it.

Thanks for that article though, was super helpful and really appreciate you replying to this thread so quickly!
