### ISSUE TITLE
Linux & NodeJS API: TypeError: Cannot read property 'localhost' of undefined at Object.stop

### ISSUE THREAD

**Issue by ibc** [sitespeedio/throttle#20]
* `@sitespeed.io/throttle` 0.5.0
* Linux Debian 8.11

Using `throttle` via NodeJS API:

```js
const throttle = require('@sitespeed.io/throttle');

throttle.stop();
```

It produces:

```
TypeError: Cannot read property 'localhost' of undefined at Object.stop
(/xxxxx/node_modules/@sitespeed.io/throttle/lib/index.js:56:21)
```

**Important:**

* It does **not** fail in OSX.
* It does **not** fail in same Linux server using it via command line.
* `throttle.start()` NodeJS API does **not** fail in Linux.

So this issue is just about `throttle.stop()` NodeJS API in Linux.

**Comment by ibc** [comment]
PR done: #21

**Comment by soulgalore** [comment]
Releases it in 0.5.1, thank you @ibc !
