### ISSUE TITLE
 throttle: command not found

### ISSUE THREAD

**Issue by kiranask** [sitespeedio/throttle#25]
I am getting throttle: command not found after executing the below command.

npm install @sitespeed.io/throttle -g
 and setting /etc/pf.conf in OSX. 

Kindly help.

**Comment by soulgalore** [comment]
Hi @kiranask and you didn't get any error etc when installing (just wanna check)?

For me:
```
 npm install @sitespeed.io/throttle -g
 throttle --version
```
works. Have you something else installed by npm globally so you can verify that it works?

Best
Peter

**Comment by weswinder** [comment]
@soulgalore I'm getting the same error here.
```
$ throttle --version
-bash: throttle: command not found

**Comment by soulgalore** [comment]
@weswinder what kind of output do you get when you install?

` npm install @sitespeed.io/throttle -g
/usr/local/bin/throttle -> /usr/local/lib/node_modules/@sitespeed.io/throttle/bin/index.js
+ @sitespeed.io/throttle@0.5.4
`

**Comment by weswinder** [comment]
@soulgalore this is my output
```
/Users/wes/.npm-packages/bin/throttle -> /Users/wes/.npm-packages/lib/node_modules/@sitespeed.io/throttle/bin/index.js
+ @sitespeed.io/throttle@0.5.4

**Comment by weswinder** [comment]
@soulgalore Seems like it's related to a PATH issue. I completely wiped Node/NPM and reinstalled. Probably more intense of a solution than it needed to be, but the issue is resolved!

**Comment by radum** [comment]
@soulgalore This can be closed.
