### ISSUE TITLE
will it influence the whole computer networks if using node.js

### ISSUE THREAD

**Issue by soundquiet** [sitespeedio/throttle#52]
I was wondering if it affects the networks outside of the node.js programs, for example, browsers, other apps. 
If it will, how can I reset the network?
Thank you!

**Comment by soulgalore** [comment]
Yes it will with the current setup. For Linux you can throttle connections just to localhost by using `--localhost`. In the next release you can do the same for OS X. One thing we could do is introduce per port.

Reset/stop everything with `throttle stop`

**Comment by soundquiet** [comment]
`await throttle.stop();` will reset my network, right?

I forgot to `stop()` in the first run, then my network became so slow. So I add `stop()` and use `4g: up:9000 down:9000 rtt:85`and run my code again. Things seem to back to normal now. But I am not sure, so I came to ask.

Thank you!

**Comment by soulgalore** [comment]
Yes stop will remove it.

**Comment by soundquiet** [comment]
got it. thank you!
Nice tool!
