### ISSUE TITLE
RTNETLINK answers: No such device

### ISSUE THREAD

**Issue by radum** [sitespeedio/throttle#55]
Hello, hope this issues finds you well.

I am running throttle in a VM (Parallels on a Mac, 5.8.0-45-generic #51~20.04.1-Ubuntu) and I always get this error:

```bash
throttle 3gfast

Using profile 3gfast
Error: Command failed: sudo tc qdisc add dev  ingress
RTNETLINK answers: No such device

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'sudo tc qdisc add dev  ingress',
  stdout: '',
  stderr: 'RTNETLINK answers: No such device\n'
}
```

Does this ring any bells, am I doing something wrong?

Thanks for your help.

**Comment by soulgalore** [comment]
Hi @radum yes it seems like getting the default interface do not work, can you test running it manually: `sudo route | grep '^default' | grep -o '[^ ]*$' | tr -d `? and then just run `route` and see what you get?
 
I used to use Parallels too but haven't upgraded to the version for Big Sur, I can have a go if you don't get it to work.

**Comment by radum** [comment]
:) Silly me, I should have run that myself. Looks like it didn't work because `route` was not available on my vanilla Ubuntu. So I had to `sudo apt install net-tools` and sorted out the problem.

I think I could add a safeguard here:

```js
const result = await shell(
    "sudo route | grep '^default' | grep -o '[^ ]*$' | tr -d '\n'",
    { shell: true }
  );
```

To make the error reporting better, or perhaps add `net-tools` to a dependencies list?

Thanks

**Comment by soulgalore** [comment]
Yes please, do you have time to make a PR for that change?

> To make the error reporting better, or perhaps add net-tools to a dependencies list?

It's there in the readme https://github.com/sitespeedio/throttle/blob/main/README.md but maybe we can highlight it more?

**Comment by radum** [comment]
> It's there in the readme https://github.com/sitespeedio/throttle/blob/main/README.md but maybe we can highlight it more?

:) I should have read the readme, classic.

Yeah I will raise a PR with the error reporting.

**Comment by radum** [comment]
```js
async function getDefaultInterface() {
  const result = await shell(
    "sudo route | grep '^default' | grep -o '[^ ]*$' | tr -d '\n'",
    { shell: true }
  );
  
  if (result.stdout.length === 0 && result.stderr.length > 0) {
    throw new Error('There was an error getting the default interface:\n\n' + result.stderr);
  }

  return result.stdout;
}
```

And the result will be:

```
node bin/index.js 3gfast
Using profile 3gfast
Error: There was an error getting the default interface

sudo: route: command not found

    at getDefaultInterface (/home/radum/projects-opensource/throttle/lib/tc.js:12:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.start (/home/radum/projects-opensource/throttle/lib/tc.js:138:19)
    at async run (/home/radum/projects-opensource/throttle/bin/index.js:145:9)
```
