### ISSUE TITLE
Error: platform win32 not supported

### ISSUE THREAD

**Issue by rekyb** [sitespeedio/throttle#83]
Hello! I got "Error: platform win32 not supported"

I use Win 10 x64 with the latest NodeJS (x64) as well. Here is the screenshot

![image](https://user-images.githubusercontent.com/29610518/233265669-5f80bbaf-887a-4121-a2e8-73455d4d9fb6.png)

Need your help. Thanks!

**Comment by soulgalore** [comment]
Hi @rekyb sorry, throttle do not work with Windows at all.

**Comment by rekyb** [comment]
I see, sorry didn't read the desc clearly. Thank you fo answering. Closing this ticket.
