### ISSUE TITLE
Doesn't work on MacOS (Sonoma 14.2 (23C64))

### ISSUE THREAD

**Issue by maxgmer** [sitespeedio/throttle#85]
When I type: 
`throttle --rtt 2000 --localhost`

I get the following:
```
Error: Command failed: sudo dnctl pipe 1 config delay 1000ms noerror
dnctl: setsockopt(IP_DUMMYNET_CONFIGURE): No space left on device

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'sudo dnctl pipe 1 config delay 1000ms noerror',
  stdout: '',
  stderr: 'dnctl: setsockopt(IP_DUMMYNET_CONFIGURE): No space left on device\n'
}
```

I have plenty of space left (30+gb free leftover RAM, even more storage).
What can I do to fix this?

**Comment by soulgalore** [comment]
Hi @maxgmer 

I asked ChatGPT: 

The error message dnctl: setsockopt(IP_DUMMYNET_CONFIGURE): No space left on device you're encountering while using the throttle command is not actually related to the physical storage or RAM space on your device. Instead, this error typically indicates an issue with the maximum number of pipes or queues that dnctl (part of the dummynet traffic shaping tool) can handle.

Here are some steps to troubleshoot and resolve the issue:

1. Check Current Pipes and Queues:
Use the command `sudo dnctl list` to check the current pipes and queues. It's possible that there are many unused or stale pipes taking up the limit.
2. Clear Existing Pipes and Queues:
If you find a lot of entries, you can clear them out. Use`sudo dnctl flush` to remove all existing pipes and queues. Be cautious with this, as it will affect all current traffic shaping rules.
3. Restart Your System:
Sometimes a simple restart can clear out any lingering issues with system resources.

Test out and see if those things helps! 
Best
Peter

**Comment by maxgmer** [comment]
1. List command doesn't show any pipes (like there is 0 of them).
2. Tried flush, same thing before and after flush.
3. Tried restarting before writing this issue :(

**Comment by maxgmer** [comment]
@soulgalore tried restarting once again, but with "Reopen windows when logging back in" disabled, it helped, thank you!
