### ISSUE TITLE
Unable to run on ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by christianlira98** [sitespeedio/throttle#91]
Hello, I am trying to use it on my machine and I get the error:

    throttle 3gslow --log
    Using profile 3gslow
    sudo ip route | awk '/default/ {print $5; exit}' | tr -d '
    '
    sudo tc qdisc del dev enp6s0 root
    sudo tc qdisc del dev enp6s0 ingress
    sudo tc qdisc del dev ifb0 root
    sudo ip route | awk '/default/ {print $5; exit}' | tr -d '
    '
    sudo modprobe ifb
    sudo ip link set dev ifb0 up
    Error: Command failed: sudo ip link set dev ifb0 up
    Cannot find device "ifb0"

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
    code: 1,
    killed: false,
    signal: null,
    cmd: 'sudo ip link set dev ifb0 up',
    stdout: '',
    stderr: 'Cannot find device "ifb0"\n'}

Any idea on how I can get this to work?

**Comment by soulgalore** [comment]
Hi @christianlira98 sorry for the late answer. Thinking maybe we can tweak it. Can you try to run this first before you run throttle:

`sudo ip link add dev ifb0 up type ifb`

**Comment by christianlira98** [comment]
Hello, @soulgalore . That worked, thank you.

**Comment by soulgalore** [comment]
Great, I did a release that fixes it.
